version: "3.9"
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-cli:
    image: redis:latest
    depends_on:
      - redis
    entrypoint: redis-cli
    command: -h redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
