version: "3.7"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_master_data:/bitnami"

  # mongodb-secondary:
  #   image: 'bitnami/mongodb:6.0.5'
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=secondary
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

  # mongodb-arbiter:
  #   image: 'bitnami/mongodb:6.0.5'
  #   depends_on:
  #     - mongodb-primary
  #   environment:
  #     - MONGODB_REPLICA_SET_MODE=arbiter
  #     - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
  #     - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=27017
  #     - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=password123
  #     - MONGODB_REPLICA_SET_KEY=replicasetkey123

volumes:
  mongodb_master_data:
    driver: local
# rs.initiate()
# rs.add('mongodb-secondary')
# rs.status().members
# rs.addArb('mongodb-arbiter')

# rs.slaveOk()
# db.getMongo().setSlaveOk()
