apiVersion: v1
kind: Service
metadata:
  name: react-webapp
  labels:
    app: react-webapp
spec:
  ports:
    - name: http
      port: 3003
  selector:
    app: react-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-webapp
spec:
  selector:
    matchLabels:
      app: react-webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: react-webapp
    spec:
      containers:
        - name: react-webapp
          image: fielcapao/microservices-design-patterns-react-webapp-service:latest
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "50m"
          env:
            - name: PORT
              value: "3003"
          ports:
            - containerPort: 3003
