version: "3"
services:
  api:
    build:
      context: ./express-server
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=4050
      - MONGO_URI=mongodb://mongo:27017/docker-node-mongo
    volumes:
      - /app/node_modules
      - ./express-server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  client:
    build:
      context: ./client-side
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client-side:/app
    depends_on:
      - api

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - client
