version: "3.8"

services:
  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:8.11.3
    volumes:
      - ./logstash/config:/usr/share/logstash/config
    ports:
      - "5000:5000"

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: kibana:8.11.3
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
