version: '3.7'

services:
  fontend:
    image: excelazmin/easy-tax-web:latest
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.constraint-label: traefik-public
        traefik.http.routers.sc-nestjs-http.rule: Host(${SITES:?No sites set})
        traefik.http.routers.sc-nestjs-http.entrypoints: http
        traefik.http.routers.sc-nestjs-http.middlewares: https-redirect
        traefik.http.routers.sc-nestjs-https.rule: Host(${SITES})
        traefik.http.routers.sc-nestjs-https.entrypoints: https
        traefik.http.routers.sc-nestjs-https.tls: "true"
        traefik.http.routers.sc-nestjs-https.tls.certresolver: le
        traefik.http.services.sc-nestjs.loadbalancer.server.port: "80"    
    environment:
      VITE_API_URL: https://api.easy-tax.pixfar.com
    networks:
     - traefik-public  
  backend:
    image: excelazmin/easy-tax-backend:latest
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: traefik-public
        traefik.enable: "true"
        traefik.constraint-label: traefik-public
        traefik.http.routers.sc-easy-tax-http.rule: Host(${API_SITES:?No sites set})
        traefik.http.routers.sc-easy-tax-http.entrypoints: http
        traefik.http.routers.sc-easy-tax-http.middlewares: https-redirect
        traefik.http.routers.sc-easy-tax-https.rule: Host(${API_SITES})
        traefik.http.routers.sc-easy-tax-https.entrypoints: https
        traefik.http.routers.sc-easy-tax-https.tls: "true"
        traefik.http.routers.sc-easy-tax-https.tls.certresolver: le
        traefik.http.services.sc-easy-tax.loadbalancer.server.port: "6050"   
    environment:
      PORT: 6050
      APP_URL: https://api.easy-tax.pixfar.com
      MONGO_CONNECTION_STRING: mongodb://<USERNAME>:<PASSWORD>@<HOST>:<PORT>
      MONGO_USERNAME: root
      MONGO_PASSWORD: mongorootPass2023
      MONGO_HOST: 202.91.42.198
      MONGO_PORT: 27017
      MONGO_DB_NAME: easy-tax #easy-tax-testing-db
      JWT_SECRET: 92b9435a4a65407b548bac2047f03e026687561e1053fadba3a9be90b9710474
      JWT_RESET_SECRET: 92b9435a4a65407b548bac2047f03e026687561e1053fadba3a9be90b9710987
      JWT_EXPIRES_IN: 1d
      EMAIL_USER: 'anamuljibon.abc.123@gmail.com'
      EMAIL_PASSWORD: 'wnrofhjypsjupjuo'
      EMAIL_PORT: 2525
      EMAIL_HOST: sandbox.smtp.mailtrap.io
      EMAIL_FROM: anamul@gmail.com
      NOTIFICATION_URL: https://fcm.googleapis.com/fcm/send
      NOTIFICATION_AUTH: AAAAF5nYUgA:APA91bEmt4HrLTxo7J02YPMhSBHaeMU5ifoNyrDLKxDgl5OnReNhQXhLTD8wr5lVB-SknmIijZI53jpU95IgvuiF-wyUvMsQS6Td8KTzYWEj1owvDAFbPqwbHjl7CbHHlrOQvPZLfOeU
      AZURE_OCR_ENDPOINT: https://azmindoc.cognitiveservices.azure.com
      AZURE_OCR_KEY: 4c33ec491b984ad98da12c375835e1bb
    volumes:
      - easy_tax_data:/usr/src/app
    networks:
     - traefik-public   
      
networks:
  traefik-public:
    name: traefik-public
    external: true  

volumes:
  easy_tax_data:



# docker build -t excelazmin/easy-tax-backend:latest .
# docker push excelazmin/easy-tax-backend:latest
# docker build -t excelazmin/easy-tax-web:latest .
# docker push excelazmin/easy-tax-web:latest


